### PR TITLE
Updates tool to support .NET Core RTM projects (csproj)

### PR DESCRIPTION
**Pull request by conniey**
* Updates tool to .NET Core RTM 1.0.0.  Requires .NET Core SDK 1.0.0 to build.
* Adds command line options to support project.json and csproj if specified.
* Looks for project.json or csproj if neither is specified.

### CODE REVIEW

**Comment by ah-** [comment]
Thanks a lot Connie that looks great!

Have you seen https://github.com/libgit2/libgit2sharp/pull/1318? It looks like the effort to bring .net core support to mainline gitversion is getting somewhere now.

**Comment by ah-** [comment]
I've just uploaded a build to nuget: https://www.nuget.org/packages/dotnet-gitversion/1.0.1

Would you mind quickly checking that it works as you expect?

**Comment by conniey** [comment]
@ah- Thanks for merging this in so quickly! I tried it out on the new projects and it appears to not be working when consumed from another project due to this https://github.com/NuGet/Home/issues/3617.

The problem packages are JetBrains.Annotations and YamlDotNet.  This is because we had used PackageTargetFallback (ie. imports in project.json) to select the correct package, but since migration to .NET CLI 1.0.0, it doesn't consider them when being restored via DotNetCliToolReference.

One way to fix these errors would be to submit a PR to JetBrains.Annotations and YamlDotNet to support netstandard.

**Error:**
```
  Restore completed in 1.1 sec for D:\git\helloworld\helloworld.csproj.
C:\Program Files\dotnet\sdk\1.0.0\NuGet.targets(97,5): error : Package JetBrains.Annotations 10.1.5 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package JetBrains.Annotations 10.1.5 supports:\r [D:\git\helloworld\helloworld.csproj]
C:\Program Files\dotnet\sdk\1.0.0\NuGet.targets(97,5): error :   - dotnet (.NETPlatform,Version=v5.0)\r [D:\git\helloworld\helloworld.csproj]
C:\Program Files\dotnet\sdk\1.0.0\NuGet.targets(97,5): error :   - net (.NETFramework,Version=v0.0)\r [D:\git\helloworld\helloworld.csproj]
C:\Program Files\dotnet\sdk\1.0.0\NuGet.targets(97,5): error :   - portable-net40+sl4+win8+wp7 (.NETPortable,Version=v0.0,Profile=Profile2)\r [D:\git\helloworld\helloworld.csproj]
C:\Program Files\dotnet\sdk\1.0.0\NuGet.targets(97,5): error :   - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328) [D:\git\helloworld\helloworld.csproj]
C:\Program Files\dotnet\sdk\1.0.0\NuGet.targets(97,5): error : Package YamlDotNet 3.9.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package YamlDotNet 3.9.0 supports:\r [D:\git\helloworld\helloworld.csproj]
C:\Program Files\dotnet\sdk\1.0.0\NuGet.targets(97,5): error :   - dotnet (.NETPlatform,Version=v5.0)\r [D:\git\helloworld\helloworld.csproj]
C:\Program Files\dotnet\sdk\1.0.0\NuGet.targets(97,5): error :   - net35 (.NETFramework,Version=v3.5)\r [D:\git\helloworld\helloworld.csproj]
C:\Program Files\dotnet\sdk\1.0.0\NuGet.targets(97,5): error :   - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259) [D:\git\helloworld\helloworld.csproj]
```

**Comment by conniey** [comment]
> Have you seen libgit2/libgit2sharp#1318? It looks like the effort to bring .net core support to mainline gitversion is getting somewhere now.

Yeah, I was excited about that... but it may be awhile because a lot of the GitVersion tools rely on Fody packages, which, from my initial effort to migrate it... uses a lot of .NET Remoting that is not supported in .NET Core. :/

**Comment by micdenny** [comment]
I didn't understand if the latest package can work or not with the net core `csproj`, in fact I take the same restore error, what's the status of this project? what do you do in your builds if you don't use this, custom powershell scripts?

**Comment by micdenny** [comment]
probably doing something like this `dotnet pack /p:Version=2.0.0`? 😞

**Comment by micdenny** [comment]
Ok I've found that every parameter passed to dotnet pack other than the one recognized by netcore itself are simply passed to msbuild:

https://github.com/dotnet/cli/blob/v1.0.3/src/dotnet/commands/dotnet-pack/PackCommand.cs#L111

so it is possible to override the version in CI simply calling `dotnet pack /p:Version=$(NuGetVersion)`

**Comment by conniey** [comment]
I've been looking into this.. and there needs to be some changes to GitVersionCore-dotnet. (I don't know where the source for it is though.) 

For the PackageTargetFallback issue:
* [JetBrains.Annotations v10.4.0](https://www.nuget.org/packages/JetBrains.Annotations/10.4.0) has been updated to support netstandard1.0. So upgrading to it should resolve the runtime issues.
* [YamlDotNet](https://github.com/aaubry/YamlDotNet/pull/244) has PR open but has been waiting for the CI build to pass before merging into master.

Also, I've talked to some tooling guys and I'll have to update the build process to pull in all of the external dependencies for dotnet-gitversion.. similar to this: 
* https://github.com/AArnott/Nerdbank.GitVersioning/tree/master/src/Nerdbank.GitVersioning.NuGet
I'll work on the PR to create a proper nuget package. It still won't run though without fixing the PackageTargetFallback issues. :/

**Comment by TAGC** [comment]
@conniey The source for GitVersionCore-dotnet is [here](https://github.com/ah-/GitVersion/tree/master/src/GitVersionCore) I think.

I opened [an issue](https://github.com/ah-/dotnet-gitversion/issues/2) requesting changes to it about a couple months ago but didn't get a response.

**Pull request merged**
